<a href="https://colab.research.google.com/github/Armeldjogo/NLP/blob/main/NLP_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Armel Nsiangani

Student ID#: 001-99-1988


NLP - HW2

Question 1:

Create a cosine similarity matrix for all of Shakespeare’s works found in the provided file. 

In [10]:
# Question 1
import glob, os
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
nltk.download('stopwords')
nltk.download('punkt')


os.chdir("/content/")
filesName = []
for namefile in glob.glob("*.txt"):
    filesName.append(namefile)


allDocuments = []
for i in range(0,len(filesName)):
  with open("/content/" + filesName[i]) as openfile:
    data = openfile.read()
    allDocuments.append(data)

stopWords = stopwords.words('english')
vect = TfidfVectorizer(min_df=1, stop_words = stopWords)                                                                                                                                                                                                   
tfidf = vect.fit_transform(allDocuments)                                                                                                                                                                                                                       
pair_similarity = tfidf * tfidf.T 
sim_matrix = pair_similarity.toarray()


print('-------------------------------------------------------------------------')
print('The cosine identity matrix is below: ')
print(sim_matrix)




-------------------------------------------------------------------------
The cosine identity matrix is below: 
[[1.         0.09898043 0.12178397 ... 0.06968641 0.08012943 0.15890955]
 [0.09898043 1.         0.1198178  ... 0.17006317 0.07518287 0.15040131]
 [0.12178397 0.1198178  1.         ... 0.10302878 0.12821051 0.22090556]
 ...
 [0.06968641 0.17006317 0.10302878 ... 1.         0.06073003 0.10442782]
 [0.08012943 0.07518287 0.12821051 ... 0.06073003 1.         0.16985445]
 [0.15890955 0.15040131 0.22090556 ... 0.10442782 0.16985445 1.        ]]


Question 2:

Write a function that takes the previous matrix and a number n as parameter (nothing else will be accepted) and return the top n similar works.

In [17]:
# Question 2
def findMostSim(m,n):
  array = np.around(m, decimals=3)
  rArray = array.reshape(-1)
  uN_Array = np.unique(rArray)
  listVal = np.flip(uN_Array)
  listVal = np.delete(listVal, np.where(listVal == 1))
  valsOfInterest = listVal[0:n]
  locVals = []
  for i in range(0,len(valsOfInterest)):
    rslt = np.where(array == valsOfInterest[i])
    locVals.append(rslt[0].tolist())
  print("The",n,"most similar works are in position: ")
  print('-----------------------------------------')
  for pos in locVals:
    print(filesName[pos[0]],'and',filesName[pos[1]])

# Print the result
findMostSim(sim_matrix,10)

The 10 most similar works are in position: 
-----------------------------------------
henry-iv-part-1_TXT_FolgerShakespeare.txt and henry-iv-part-2_TXT_FolgerShakespeare.txt
venus-and-adonis_TXT_FolgerShakespeare.txt and shakespeares-sonnets_TXT_FolgerShakespeare.txt
shakespeares-sonnets_TXT_FolgerShakespeare.txt and lucrece_TXT_FolgerShakespeare.txt
venus-and-adonis_TXT_FolgerShakespeare.txt and lucrece_TXT_FolgerShakespeare.txt
henry-vi-part-2_TXT_FolgerShakespeare.txt and henry-vi-part-3_TXT_FolgerShakespeare.txt
henry-vi-part-1_TXT_FolgerShakespeare.txt and henry-vi-part-2_TXT_FolgerShakespeare.txt
richard-iii_TXT_FolgerShakespeare.txt and henry-vi-part-3_TXT_FolgerShakespeare.txt
richard-ii_TXT_FolgerShakespeare.txt and richard-iii_TXT_FolgerShakespeare.txt
richard-ii_TXT_FolgerShakespeare.txt and henry-vi-part-3_TXT_FolgerShakespeare.txt
the-merry-wives-of-windsor_TXT_FolgerShakespeare.txt and henry-iv-part-2_TXT_FolgerShakespeare.txt


Question 3:

Using the code from the Language Models II class, train two simple language models using all of the files.

In [19]:
# Question 3
import glob, os
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import random
import nltk
#nltk.download('punkt')
from nltk import bigrams, trigrams
from collections import Counter, defaultdict

# Import and store all shakespear work into 1 doc
os.chdir("/content/")
filesName = []
for namefile in glob.glob("*.txt"):
    filesName.append(namefile)

with open("/content/" + filesName[0]) as openfile:
  allDocuments = openfile.readlines()

for i in range(1,len(filesName)):
  with open("/content/" + filesName[i]) as openfile:
    data = openfile.readlines()
    allDocuments.append(data)

allDoc_split = []
for sent in allDocuments:
  sent = ''.join(sent)
  line = sent.split(" ")
  allDoc_split.append(line)

# Create a placeholder for model
model_1 = defaultdict(lambda: defaultdict(lambda: 0))
model_2 = defaultdict(lambda: defaultdict(lambda: 0))
# Count frequency of co-occurence  
for sentence in allDoc_split:
    # Using trigrams
    for w1, w2, w3 in trigrams(sentence, pad_right=True, pad_left=True):
        model_1[(w1, w2)][w3] += 1
    # Using bigrams
    for w1, w2 in bigrams(sentence, pad_right=True, pad_left=True):
        model_2[(w1)][w2] += 1 

# Let's transform the counts to probabilities
# Trigrmas
for w1_w2 in model_1:
    total_count = float(sum(model_1[w1_w2].values()))
    for w3 in model_1[w1_w2]:
        model_1[w1_w2][w3] /= total_count 
# Bigrams
for w1_w2 in model_2:
    total_count = float(sum(model_2[w1_w2].values()))
    for w3 in model_2[w1_w2]:
        model_2[w1_w2][w3] /= total_count

# Testing the models

#print('Using Trigrams')
#print('-----------------')
#dict(model_1["But","now"])


print('Using Bigrams')
print('-----------------')
dict(model_2["king"])


Using Bigrams
-----------------


{'Charles': 0.005813953488372093,
 'Charles,\nFor': 0.005813953488372093,
 'I': 0.011627906976744186,
 "I'll": 0.005813953488372093,
 'King': 0.005813953488372093,
 'adopt': 0.005813953488372093,
 'again,\nAnd': 0.005813953488372093,
 'and': 0.1744186046511628,
 'and\na': 0.005813953488372093,
 'at': 0.023255813953488372,
 'be': 0.01744186046511628,
 'blest': 0.005813953488372093,
 'but': 0.023255813953488372,
 'by': 0.005813953488372093,
 'can': 0.005813953488372093,
 'christen': 0.005813953488372093,
 'crowned': 0.005813953488372093,
 'dead?\n\nPISTOL\nAs': 0.005813953488372093,
 'double,': 0.005813953488372093,
 'engenders': 0.005813953488372093,
 'for': 0.011627906976744186,
 'has': 0.005813953488372093,
 'here': 0.005813953488372093,
 'hereafter!\n\nBANQUO\nGood': 0.005813953488372093,
 'himself': 0.005813953488372093,
 'his': 0.005813953488372093,
 'in': 0.029069767441860465,
 'indeed,': 0.005813953488372093,
 'inter': 0.005813953488372093,
 'is': 0.040697674418604654,
 'is,\nBei

Question 4:

Write a function that takes the following three parameters: model, list of start words, number of sentences to generate.

In [35]:
# Question 4
def makeSentence(m,w,n):
  sentence_finished = False
  n = float(n)
  sent = [0]*int(n)
  tmp = 0.0
  # Trigram
  if m == 1:
    text = w
    while not sentence_finished: 
      r = 0.01 
      for word in model_1[tuple(text[-2:])].keys():
        accumulator = .0
        accumulator += model_1[tuple(text[-2:])][word]
        if accumulator >= r and tmp <= (n-1):
          x = text + [word]
          sent[int(tmp)] = x
          tmp += 1.0
        if tmp == (n):
          sentence_finished = True
          break
  # Bigram
  elif m == 2:
      text = w
      while not sentence_finished: 
        r = 0.001
        for word in model_2[text[0]].keys():
          accumulator = .0
          accumulator += model_2[text[0]][word]
          if accumulator >= r and tmp <= (n-1):
            x = text + [word]
            sent[int(tmp)] = x
            tmp += 1.0      
          if tmp == (n):
            sentence_finished = True
            break
  return sent


# Testing the function 
text_1 = ["king","of"]
text_2 = ["that"]

tri = makeSentence(1,text_1,5)
big = makeSentence(2,text_2,10)

print('5 sentences with the Trigram model')
print('-------------------------------------')
print(tri)
print()
print()
print('10 sentences with the Bigram model')
print('-------------------------------------')
print(big)


5 sentences with the Trigram model
-------------------------------------
[['king', 'of', 'pygmies,\n'], ['king', 'of', 'smiles,'], ['king', 'of', 'courtesy,\nand'], ['king', 'of', 'honor.\nNo'], ['king', 'of', 'it?\n\nBASTARD,']]


10 sentences with the Bigram model
-------------------------------------
[['that', 'good'], ['that', 'is'], ['that', 'we'], ['that', 'time'], ['that', 'with'], ['that', 'this'], ['that', 'will'], ['that', 'you'], ['that', 'your'], ['that', 'I']]
